services:
  mongodb:
    image: mongo:latest
    container_name: agrichat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agrichat-net
    restart: unless-stopped

  backend:
    build:
      context: ./agrichat-backend
    container_name: agrichat-backend
    network_mode: host
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://localhost:27017/agrichat
      - USE_HTTPS=${USE_HTTPS:-false}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_HOST=localhost:11434
    # Add restart policy for production
    restart: unless-stopped
    # GPU Support
    runtime: nvidia
    # Override CMD for HTTPS when USE_HTTPS=true
    command: >
      sh -c "
        if [ \"$$USE_HTTPS\" = \"true\" ]; then
          uvicorn app:app --host 0.0.0.0 --port 8443 --ssl-keyfile=ssl/private.key --ssl-certfile=ssl/certificate.crt
        else
          uvicorn app:app --host 0.0.0.0 --port 8000
        fi
      "

networks:
  agrichat-net:

volumes:
  mongodb_data:
