services:
  mongodb:
    image: mongo:latest
    container_name: agrichat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agrichat-net
    restart: unless-stopped

  backend:
    build:
      context: ./agrichat-backend
    container_name: agrichat-backend
    network_mode: host
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://localhost:27017/agrichat
      - USE_HTTPS=${USE_HTTPS:-false}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_HOST=localhost:11434
      - CUDA_VISIBLE_DEVICES=0,1
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    command: >
      sh -c "
        if [ \"$$USE_HTTPS\" = \"true\" ]; then
          gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8443 --workers 4 --keyfile=ssl/private.key --certfile=ssl/certificate.crt
        else
          gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --worker-connections 1000 --max-requests 1000 --max-requests-jitter 100
        fi
      "

networks:
  agrichat-net:

volumes:
  mongodb_data:
