version: '3.8'

services:
  backend:
    build:
      context: ./agrichat-backend
    container_name: agrichat-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - agrichat-net

  frontend:
    build:
      context: ./agrichat-frontend
    container_name: agrichat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - agrichat-net

networks:
  agrichat-net:
