services:
  - type: web
    name: agrichat-backend
    runtime: python-3.11.9
    buildCommand: ""
    startCommand: "gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000 --timeout 120"
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
    plan: free
    rootDir: agrichat-backend