labels = [
  "Crop",
  "Livestock",
  "Pest",
  "Disease",
  "Weed",
  "Beneficial Organism",
  "Symptom / Damage Descriptor",
  "Affected Part",
  "Abiotic Stress Factor",
  "Agrochemical Active Ingredient",
  "Product Brand Name",
  "Fertilizer / Nutrient",
  "Bio-product / Organic Treatment",
  "Veterinary Medicine",
  "Agricultural Practice",
  "Farming System",
  "Farming Equipment",
  "Quantity / Rate",
  "Unit of Measurement",
  "Temporal Expression",
  "Soil Attribute",
  "Weather / Climatic Factor",
  "Geographic Location",
  "Organization / Institution",
  "Government Scheme",
  "Economic Factor"
]
